[package]
name = "enumerate"
version = "0.1.0"
authors = ["Jake Marsden <jakemarsdenjm@gmail.com>"]
edition = "2021"
publish = false

[dependencies]
enumerate_derive = { path = "../enumerate_derive" }
