[package]
name = "jakescript"
version = "0.1.0"
authors = ["Jake Marsden <jakemarsdenjm@gmail.com>"]
edition = "2021"
publish = false

[dependencies]
enumerate = { path = "../enumerate" }
ansi_term = "0.12"

[dev-dependencies]
utf8-chars = "1.0"
walkdir = "2.3"
