use crate::simple_enumeration;

// TODO: Some variants should only be _contextually_ disallowed as identifiers, i.e. in certain
//  circumstances they should be allowed as identifiers. Unfortunately, this may need to be handled
//  by the parser.
simple_enumeration!(pub Keyword {
    As => "as",
    Async => "async",
    Await => "await",
    Break => "break",
    Case => "case",
    Catch => "catch",
    Class => "class",
    Const => "const",
    Continue => "continue",
    Debugger => "debugger",
    Default => "default",
    Delete => "delete",
    Do => "do",
    Else => "else",
    Enum => "enum",
    Export => "export",
    Extends => "extends",
    Finally => "finally",
    For => "for",
    From => "from",
    Function => "function",
    Get => "get",
    If => "if",
    Implements => "implements",
    Import => "import",
    In => "in",
    InstanceOf => "instanceof",
    Interface => "interface",
    Let => "let",
    New => "new",
    Of => "of",
    Package => "package",
    Private => "private",
    Protected => "protected",
    Public => "public",
    Return => "return",
    Set => "set",
    Static => "static",
    Super => "super",
    Switch => "switch",
    Target => "target",
    This => "this",
    Throw => "throw",
    Try => "try",
    TypeOf => "typeof",
    Var => "var",
    Void => "void",
    While => "while",
    With => "with",
    Yield => "yield",
});
