[package]
name = "jakescript-cli"
version = "0.1.0"
authors = ["Jake Marsden <jakemarsdenjm@gmail.com>"]
edition = "2021"
publish = false

[dependencies]
jakescript = { path = "../jakescript" }
ansi_term = "0.12"
fallible-iterator = "0.2"
serde_json = "1.0"
serde_yaml = "0.8"
utf8-chars = "1.0"
