console.assert(String);
console.assertEqual(String(false), "false");
console.assertEqual(String(true), "true");
console.assertEqual(String(0), "0");
console.assertEqual(String(-1), "-1");
console.assertEqual(String(+1), "1");
console.assertEqual(String(NaN), "NaN");
console.assertEqual(String(-Infinity), "-Infinity");
console.assertEqual(String(+Infinity), "Infinity");
console.assertEqual(String({}), "[object Object]");
console.assertEqual(String(""), "");
console.assertEqual(String("a"), "a");
// TODO: console.assertEqual(String(function () {}), "function () {}");
console.assertEqual(String(null), "null");
console.assertEqual(String(undefined), "undefined");
console.assertEqual(String(), "");

console.assert("".charAt);
console.assertEqual("Hello, world!".charAt(0), "H");
console.assertEqual("Hello, world!".charAt(1), "e");
console.assertEqual("Hello, world!".charAt(12), "!");
console.assertEqual("Hello, world!".charAt(13), "");
console.assertEqual("Hello, world!".charAt(99), "");
console.assertEqual("Hello, world!".charAt(-1), "");
console.assertEqual("Hello, world!".charAt(NaN), "H");
console.assertEqual("Hello, world!".charAt(+Infinity), "");
console.assertEqual("Hello, world!".charAt(-Infinity), "");
console.assertEqual("Hello, world!".charAt(), "H");
console.assertEqual("Hello, world!".charAt(undefined), "H");
console.assertEqual("Hello, world!".charAt(null), "H");
console.assertEqual("Hello, world!".charAt(true), "e");
console.assertEqual("Hello, world!".charAt(false), "H");
console.assertEqual("Hello, world!".charAt("7"), "w");
console.assertEqual("Hello, world!".charAt("99"), "");
console.assertEqual("Hello, world!".charAt("-1"), "");

console.assertEqual("".length, 0);
console.assertEqual("Hello, world!".length, 13);
console.assertEqual(("Hello, " + "world" + "!").length, 13);
let foo = "foo";
console.assertEqual(foo.length, 3);
foo.length = 123;
console.assertEqual(foo.length, 3);

console.assert("".substring);
console.assertEqual("Hello, world!".substring(), "Hello, world!");
console.assertEqual("Hello, world!".substring(7), "world!");
console.assertEqual("Hello, world!".substring(7, 12), "world");
console.assertEqual("Hello, world!".substring(12, 7), "world");
console.assertEqual("Hello, world!".substring(99), "");
console.assertEqual("Hello, world!".substring(7, 99), "world!");
console.assertEqual("Hello, world!".substring(99, 7), "world!");
console.assertEqual("Hello, world!".substring(99, 99), "");
