console.assert(String);
console.assertEqual(String(false), "false");
console.assertEqual(String(true), "true");
console.assertEqual(String(0), "0");
console.assertEqual(String(-1), "-1");
console.assertEqual(String(+1), "1");
console.assertEqual(String(NaN), "NaN");
console.assertEqual(String(-Infinity), "-Infinity");
console.assertEqual(String(+Infinity), "Infinity");
console.assertEqual(String({}), "[object Object]");
console.assertEqual(String(""), "");
console.assertEqual(String("a"), "a");
// TODO: console.assertEqual(String(function () {}), "function () {}");
console.assertEqual(String(null), "null");
console.assertEqual(String(undefined), "undefined");
console.assertEqual(String(), "");

console.assert(String.charAt);
console.assertEqual(String.charAt("Hello, world!", 0), "H");
console.assertEqual(String.charAt("Hello, world!", 1), "e");
console.assertEqual(String.charAt("Hello, world!", 12), "!");
console.assertEqual(String.charAt("Hello, world!", 13), "");
console.assertEqual(String.charAt("Hello, world!", 99), "");
console.assertEqual(String.charAt("Hello, world!", -1), "");
console.assertEqual(String.charAt("Hello, world!", NaN), "H");
console.assertEqual(String.charAt("Hello, world!", +Infinity), "");
console.assertEqual(String.charAt("Hello, world!", -Infinity), "");
console.assertEqual(String.charAt("Hello, world!"), "H");
console.assertEqual(String.charAt("Hello, world!", undefined), "H");
console.assertEqual(String.charAt("Hello, world!", null), "H");
console.assertEqual(String.charAt("Hello, world!", true), "e");
console.assertEqual(String.charAt("Hello, world!", false), "H");
console.assertEqual(String.charAt("Hello, world!", "7"), "w");
console.assertEqual(String.charAt("Hello, world!", "99"), "");
console.assertEqual(String.charAt("Hello, world!", "-1"), "");

console.assertEqual("".length, 0);
console.assertEqual("Hello, world!".length, 13);
console.assertEqual(("Hello, " + "world" + "!").length, 13);
