console.assert(isNaN);
console.assertEqual(isNaN(7), false);
console.assertEqual(isNaN(Infinity), false);
console.assertEqual(isNaN(-Infinity), false);
console.assertEqual(isNaN(NaN), true);
console.assertEqual(isNaN(null), true);
console.assertEqual(isNaN(undefined), true);
console.assertEqual(isNaN(true), true);
console.assertEqual(isNaN(false), true);
console.assertEqual(isNaN("Hello, world!"), true);
console.assertEqual(isNaN({}), true);
console.assertEqual(isNaN(function () {}), true);
console.assertEqual(isNaN(isNaN), true);
console.assertEqual(isNaN, isNaN);
