console.assert(Boolean);
console.assertEqual(Boolean(false), false);
console.assertEqual(Boolean(true), true);
console.assertEqual(Boolean(0), false);
console.assertEqual(Boolean(-1), true);
console.assertEqual(Boolean(+1), true);
console.assertEqual(Boolean(NaN), false);
console.assertEqual(Boolean(-Infinity), true);
console.assertEqual(Boolean(+Infinity), true);
console.assertEqual(Boolean({}), true);
console.assertEqual(Boolean(""), false);
console.assertEqual(Boolean("a"), true);
console.assertEqual(Boolean("false"), true);
console.assertEqual(Boolean(function () {}), true);
console.assertEqual(Boolean(null), false);
console.assertEqual(Boolean(undefined), false);
console.assertEqual(Boolean(), false);
