console.assert(String);
console.assert(String(false) === "false");
console.assert(String(true) === "true");
console.assert(String(0) === "0");
console.assert(String(-1) === "-1");
console.assert(String(+1) === "1");
console.assert(String(NaN) === "NaN");
console.assert(String(-Infinity) === "-Infinity");
console.assert(String(+Infinity) === "Infinity");
console.assert(String({}) === "[object Object]");
console.assert(String("") === "");
console.assert(String("a") === "a");
// TODO: console.assert(String(function () {}) === "function () {}");
console.assert(String(null) === "null");
console.assert(String(undefined) === "undefined");
console.assert(String() === "");

console.assert(String.charAt);
console.assert(String.charAt("Hello, world!", 0) === "H");
console.assert(String.charAt("Hello, world!", 1) === "e");
console.assert(String.charAt("Hello, world!", 12) === "!");
console.assert(String.charAt("Hello, world!", 13) === "");
console.assert(String.charAt("Hello, world!", 99) === "");
console.assert(String.charAt("Hello, world!", -1) === "");
console.assert(String.charAt("Hello, world!", NaN) === "H");
console.assert(String.charAt("Hello, world!", +Infinity) === "");
console.assert(String.charAt("Hello, world!", -Infinity) === "");
console.assert(String.charAt("Hello, world!") === "H");
console.assert(String.charAt("Hello, world!", undefined) === "H");
console.assert(String.charAt("Hello, world!", null) === "H");
console.assert(String.charAt("Hello, world!", true) === "e");
console.assert(String.charAt("Hello, world!", false) === "H");
console.assert(String.charAt("Hello, world!", "7") === "w");
console.assert(String.charAt("Hello, world!", "99") === "");
console.assert(String.charAt("Hello, world!", "-1") === "");

console.assert("".length === 0);
console.assert("Hello, world!".length === 13);
console.assert(("Hello, " + "world" + "!").length === 13);
