name: CI
on:
  - push
  - pull_request

jobs:
  build:
    name: "Rust ${{ matrix.rust }} on ${{ matrix.os }}"
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        rust:
          - nightly
        os:
          - macos-10.15
          - ubuntu-20.04
          - windows-2019

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
          profile: minimal
          components: clippy, rustfmt
          override: true

      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --workspace

      - name: Test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --workspace -- --nocapture

      - name: Lint
        uses: actions-rs/cargo@v1
        with:
          # See: https://github.com/rust-lang/cargo/issues/5034
          # See: https://github.com/rust-lang/cargo/issues/8415
          command: clippy
          args: --all-features --all-targets --workspace -- -Dwarnings -Dclippy::all -Dclippy::pedantic -Dclippy::missing-panics-doc -Aclippy::if-not-else -Aclippy::missing-errors-doc -Aclippy::module-name-repetitions -Aclippy::must-use-candidate

      - name: Check format
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check
